added shoppingcart and cartitem entities anf functionality for them
polikarpov13/Online-Book-Store pull request #11
Opened 2024-02-07 11:01 UTC by polikarpov13

2024-02-07 11:44 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/model/ShoppingCart.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, name= name = "is_deleted")

```
cause hibernate want to match this value with isDeleted column

2024-02-07 11:44 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/model/CartItem.java
> +    @Column(nullable = false)
same here

2024-02-07 11:44 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/model/ShoppingCart.java
> +@SQLDelete(sql = "UPDATE sopping_carts set is_deleted = TRUE WHERE id = ?")
```suggestion
@SQLDelete(sql = "UPDATE shopping_carts set is_deleted = TRUE WHERE id = ?")

```
be more attentive

2024-02-08 18:00 UTC, Vasul-Pankiv requested changes

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/dto/cartitem/CartItemDto.java
> +    private int quantity;
remove empty lines

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/dto/cartitem/CartItemDto.java
> +    @Min(1)
its not necessary here
```suggestion
```

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/dto/shoppingcart/PrintShoppingCartDto.java
> +    private Set<CartItemDto> cartItemDtos;
remove empty lines

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/dto/shoppingcart/ShoppingCartDto.java
I think you can delete it and use only printShoppingCartDto (but rename it to ShoppingCartDto) but its up to you

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/dto/shoppingcart/ShoppingCartDto.java
> +    private Set<Long> cartItemIds;
empty lines

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/mapper/ShoppingCartMapper.java
> +    }
Why do you need all of those methods? Methods above should work correct

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/repository/shoppingcart/ShoppingCartRepository.java
> +            + "WHERE sc.user.id = (:id)")
```suggestion
    @Query("SELECT sc FROM ShoppingCart sc "
            + "LEFT JOIN FETCH sc.user u "
            + "LEFT JOIN FETCH sc.cartItems ci "
            + "LEFT JOIN FETCH ci.book b "
            + "WHERE u.id = (:id)")

```

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/java/book/store/onlinebookstore/service/shoppingcart/ShoppingCartServiceImpl.java
> +    }
you need to create another private method here to return a shoppingCart model and reuse this mathod into addItemToCart method, cause mapping from model to dto and then again to dto is not good

2024-02-08 18:00 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/13-create-shopping-cart-table.yaml
> +                    nullable: false
add empty lines to all your .yaml files

2024-02-10 11:36 UTC, olekskov requested changes

2024-02-10 11:36 UTC, olekskov commented on src/main/java/book/store/onlinebookstore/mapper/ShoppingCartMapper.java
> +    }
These methods should be covered by relevant model mappers. In our case it's CartItemMapper and UserMapper.
Please check how to use one mapper in another

2024-02-10 12:26 UTC, olekskov approved these changes

2024-02-12 11:07 UTC, merged